New procrustes
gibsramen/q2-diversity pull request #1
Opened 2023-03-11 00:40 UTC by wasade

Tests and an action to drive the method

@gibsramen, how's this look? 

We could compute disparity for the paired samples, but it isn't directly usable in emperor as its procrustes action requires two ordinations for input. In this case, we merge the ordination space into a single object (which I think is what we want to do...)

2023-03-14 18:09 UTC, gibsramen requested changes
Thanks! Minor documentation issue but aside from that I think this is great.

2023-03-14 18:09 UTC, gibsramen commented on q2_diversity/plugin_setup.py
> +        'pairing': ("The metadata column describing the pair a sample may "
Description of `pairing` parameter needs a fix.

2023-03-25 00:00 UTC, wasade commented on q2_diversity/plugin_setup.py
> +        'pairing': ("The metadata column describing the pair a sample may "
Done!

2023-03-25 00:01 UTC, wasade commented
Hey @gibsramen, I think this is good now

2023-03-27 16:58 UTC, gibsramen commented
Agreed, thanks!

2023-03-27 16:58 UTC, merged